### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by ggosiang** [jupyterlab/jupyterlab-git#419] opened 2019-09-30 03:29 UTC
I've installed and enabled jupyterlab-git extension in my jupyterlab,
then I can see the `git icon in left panel`, `git option in menubar`, and `git clone button`.

but when I want to use git clone button to clone some public repos, 
then it always show `Clone failed` without any error message.

I don't know how to solve it, need help!

**Comment by ggosiang** [comment] 2019-10-02 03:37
when performing some functionalities like pull, push, clone, ...

then logs always show 404...

```
[W 11:33:50.481 LabApp] 404 POST /git/all_history?1569987230475 (::1) 3.43ms referer=http://localhost:8888/lab
[W 11:34:01.038 LabApp] 404 POST /git/all_history?1569987241031 (::1) 2.92ms referer=http://localhost:8888/lab
[W 11:34:04.921 LabApp] 404 POST /git/push?1569987244918 (::1) 1.28ms referer=http://localhost:8888/lab
[W 11:34:18.836 LabApp] 404 POST /git/show_top_level?1569987258831 (::1) 2.04ms referer=http://localhost:8888/lab
[W 11:34:33.727 LabApp] 404 POST /git/show_top_level?1569987273723 (::1) 1.30ms referer=http://localhost:8888/lab
[W 11:34:38.047 LabApp] 404 POST /git/all_history?1569987278038 (::1) 2.46ms referer=http://localhost:8888/lab
[W 11:34:47.294 LabApp] 404 POST /git/show_top_level?1569987287290 (::1) 1.88ms referer=http://localhost:8888/lab
[W 11:34:55.397 LabApp] 404 POST /git/clone?1569987295390 (::1) 2.86ms referer=http://localhost:8888/lab
```

**Comment by fcollonval** [comment] 2019-10-03 05:10
Hey, the server extension is probably not installed. You could check it using 
```bash
jupyter serverextension list
```
If you have installed the python package through pip, you will need to enable the serverextension:
```bash
jupyter serverextension enable --py juoyterlab_git
```

**Comment by ggosiang** [comment] 2019-10-03 05:23
yes, already enabled it
but still got same error

```
$ jupyter serverextension list
config dir: /home/jovyan/.jupyter
    jupyterlab_git  enabled
    - Validating...
      jupyterlab_git  OK

$ jupyter labextension list
JupyterLab v1.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyterlab/git v0.8.1  enabled  OK
```

**Comment by Snapple49** [comment] 2019-10-03 11:09
I'm also getting this error after installing, enabling and rebuilding lab. The buttons are there in the ui, but cloning repo fails with 404: 
```[W 11:02:31.696 NotebookApp] 404 POST /git/all_history?1570100551689 (10.10.0.33) 3.33ms referer=https://<public url redacted>/lab?```

**Comment by flight505** [comment] 2019-10-03 11:36
same here - not able to add a repo

**Comment by fcollonval** [comment] 2019-10-19 14:17
I'm closing this as @flight505 has proposed a solution. If anybody still encounters this issue, feel free to open an new issue.

**Closed by fcollonval** 2019-10-19 14:17 UTC

**Comment by alex-kravets** [comment] 2019-12-01 04:42
The problem is still present even after the new Jupyter Lab release 1.2.3. So nothing has changed - this issue should be opened again.

**Comment by fcollonval** [comment] 2019-12-01 11:41
@alex-kravets could you please open a new issue? And provide as much information as possible on your installation and the error message you are getting.

**Comment by alxfed** [comment] 2020-01-25 15:41
It's not a _new_ issue it is **THE SAME** issue.
