### ISSUE TITLE
Jupyterlab 3.0.0 support

### ISSUE THREAD

**Issue by dipanjank** [jupyterlab/jupyterlab-git#852] opened 2020-12-30 07:38 UTC
## Is your feature request related to a problem? Please describe.Jupyterlab 3.0.0 was released on Dec 24, 2020. This extension is not compatible.

```bash
Building jupyterlab assets (production, minimized)
$ jupyter labextension install @jupyterlab/git
An error occured.
ValueError: The extension "@jupyterlab/git" does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                  Extension        Package
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/application
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/apputils
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/codemirror
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/console
>=5.0.0 <5.1.0              >=4.0.0 <5.0.0   @jupyterlab/coreutils
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/filebrowser
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/mainmenu
>=6.0.0 <6.1.0              >=5.0.0 <6.0.0   @jupyterlab/services
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/settingregistry
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/terminal
>=3.0.0 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/ui-components
>=17.0.1 <18.0.0            >=16.9.0 <16.10.0react
>=17.0.1 <18.0.0            >=16.9.0 <16.10.0react-dom
See the log file for details:  /tmp/jupyterlab-debug-35jegu1z.log
$ 
```
## Describe the solution you'd like
Can we please release a compatible version?

## Describe alternatives you've considered
There are no alternatives.

## Additional context

These are not relevant.

**Comment by fcollonval** [comment] 2020-12-30 09:20
This is a duplicate of #779 
Please subscribe to that issue to be notified.

**Closed by fcollonval** 2020-12-30 09:20 UTC
Labels: type:Enhancement

**Comment by dipanjank** [comment] 2020-12-30 09:26
Ah sorry, thanks for the update.
