### ISSUE TITLE
Jupyterlab 3 Compatibility

### ISSUE THREAD

**Issue by PUKL-XXXL** [jupyterlab/jupyterlab-git#857] opened 2021-01-19 06:08 UTC
## Is your feature request related to a problem? Please describe.

The jupyterlab-git package is currently not supported by Jupyterlab 3 and can not be installed/used with it.

## Describe the solution you'd like

It would be great to have a jupyterlab-git package in pip/pypi that is compatible with Jupyterlab 3

## Describe alternatives you've considered

I could not come up with any workarounds.

**Comment by ianhi** [comment] 2021-01-19 06:39
Hi @PUKL-XXXL 

This is a duplicate of #779

Please subscribe to that issue using the area to the right of the issue for updates.

**Closed by ianhi** 2021-01-19 06:39 UTC
Labels: type:Enhancement
