### ISSUE TITLE
Not able to open the .gitignore file through the git extension tab

### ISSUE THREAD

**Issue by rahrad123** [jupyterlab/jupyterlab-git#1239] opened 2023-05-01 21:04 UTC
## Description

Not able to open the .gitignore file through the git extension tab unless c.ContentsManager.allow_hidden is set to True. We observed this on JupyterLab with version 3.5.0 and notebook version 6.4.12

## Reproduce

1. Open the JupyterLab Interface with the jupuyterlab-git extension installed.
2. Clone a repo using the clone repository option on the left side of the JupyterLab UI
3. Open the directory on the file manager 
4. Click on the Open .gitignore in the Git Tab on the Task Bar
5. The file does not open up.

## Expected behavior

The .gitignore file should open as a editable file when Open .gitignore in the Git Tab on the Task Bar.

## Context

- Python package version:
Python version 3.10.8
Jupyterlab 3.5.0

- Extension version:
Jupyterlab-git 0.41.0
- Git version: 2.39.2
- Operating System and its version:

<details><summary>Command Line Output</summary>
<pre>
(base) [ssl]$ jupyter-lab --certfile=~/ssl/mycert.pem --keyfile ~/ssl/mykey.key
[I 2023-05-01 19:02:10.765 ServerApp] jupyter_server_fileid | extension was successfully linked.
[I 2023-05-01 19:02:10.770 ServerApp] jupyter_server_mathjax | extension was successfully linked.
[I 2023-05-01 19:02:10.774 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-05-01 19:02:10.778 ServerApp] jupyter_server_ydoc | extension was successfully linked.
[I 2023-05-01 19:02:10.784 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-05-01 19:02:10.784 ServerApp] jupyterlab_git | extension was successfully linked.
[W 2023-05-01 19:02:10.786 NotebookApp] 'kernel_spec_manager_class' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-05-01 19:02:10.787 NotebookApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-05-01 19:02:10.787 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-05-01 19:02:10.793 ServerApp] ServerApp.iopub_data_rate_limit config is deprecated in 2.0. Use ZMQChannelsWebsocketConnection.iopub_data_rate_limit.
[W 2023-05-01 19:02:10.793 ServerApp] ServerApp.password config is deprecated in 2.0. Use PasswordIdentityProvider.hashed_password.
[I 2023-05-01 19:02:10.793 ServerApp] nbclassic | extension was successfully linked.
[I 2023-05-01 19:02:10.793 ServerApp] nbdime | extension was successfully linked.
[I 2023-05-01 19:02:10.795 ServerApp] Writing Jupyter server cookie secret to /home/ec2-user/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2023-05-01 19:02:11.827 ServerApp] sparkmagic | extension was found and enabled by notebook_shim. Consider moving the extension to Jupyter Server's extension paths.
[I 2023-05-01 19:02:11.827 ServerApp] sparkmagic | extension was successfully linked.
[I 2023-05-01 19:02:11.827 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-05-01 19:02:11.829 ServerApp] Using EnvironmentKernelSpecManager...
[I 2023-05-01 19:02:11.829 ServerApp] Started periodic updates of the kernel list (every 3 minutes).
[I 2023-05-01 19:02:11.862 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-05-01 19:02:11.863 FileIdExtension] Configured File ID manager: ArbitraryFileIdManager
[I 2023-05-01 19:02:11.863 FileIdExtension] ArbitraryFileIdManager : Configured root dir: /home/ec2-user/ssl
[I 2023-05-01 19:02:11.863 FileIdExtension] ArbitraryFileIdManager : Configured database path: /home/ec2-user/.local/share/jupyter/file_id_manager.db
[I 2023-05-01 19:02:11.863 FileIdExtension] ArbitraryFileIdManager : Successfully connected to database file.
[I 2023-05-01 19:02:11.864 FileIdExtension] ArbitraryFileIdManager : Creating File ID tables and indices with journal_mode = DELETE
[I 2023-05-01 19:02:11.872 FileIdExtension] Attached event listeners.
[I 2023-05-01 19:02:11.873 ServerApp] jupyter_server_fileid | extension was successfully loaded.
[I 2023-05-01 19:02:11.873 ServerApp] jupyter_server_mathjax | extension was successfully loaded.
[I 2023-05-01 19:02:11.874 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-05-01 19:02:11.875 ServerApp] jupyter_server_ydoc | extension was successfully loaded.
[I 2023-05-01 19:02:11.876 LabApp] JupyterLab extension loaded from /home/ec2-user/anaconda3/lib/python3.10/site-packages/jupyterlab
[I 2023-05-01 19:02:11.876 LabApp] JupyterLab application directory is /home/ec2-user/anaconda3/share/jupyter/lab
[I 2023-05-01 19:02:11.879 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-05-01 19:02:11.885 ServerApp] jupyterlab_git | extension was successfully loaded.
[I 2023-05-01 19:02:11.893 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-05-01 19:02:11.949 ServerApp] nbdime | extension was successfully loaded.
[I 2023-05-01 19:02:11.949 ServerApp] sparkmagic extension enabled!
[I 2023-05-01 19:02:11.950 ServerApp] sparkmagic | extension was successfully loaded.
[I 2023-05-01 19:02:11.950 ServerApp] The port 8888 is already in use, trying another port.
[I 2023-05-01 19:02:11.950 ServerApp] Serving notebooks from local directory: /home/ec2-user/ssl
[I 2023-05-01 19:02:11.950 ServerApp] Jupyter Server 2.0.6 is running at:
[I 2023-05-01 19:02:11.951 ServerApp] https://localhost:8889/lab
[I 2023-05-01 19:02:11.951 ServerApp]  or https://127.0.0.1:8889/lab
[I 2023-05-01 19:02:11.951 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-05-01 19:02:11.956 ServerApp] No web browser found: could not locate runnable browser.
[I 2023-05-01 19:02:11.956 ServerApp] Starting initial scan of virtual environments...

**Comment by fcollonval** [comment] 2023-08-10 06:47
As we respect the server configuration (because we use it to get current file content), this one is gonna be tricky to work around.

As you mention for now, the workaround is to run JupyterLab/Notebook with the option: `c.ContentsManager.allow_hidden = True`.

**Comment by fcollonval** [comment] 2023-08-23 10:35
Closing as duplicate of https://github.com/jupyterlab/jupyterlab-git/issues/1168

**Closed by fcollonval** 2023-08-23 10:35 UTC
Labels: bug
