### ISSUE TITLE
extension fails when using black in pre-commit-hook

### ISSUE THREAD

**Issue by sutiv** [jupyterlab/jupyterlab-git#544] opened 2020-02-26 11:44 UTC
## Description
The extension fails with `Unhandeled error` if a pre-commit-hook is exectuted and does exit with non-zero. This happens if black changes files, because they are not correctly formatted.

A fix is to add `entry: bash -c 'black "$@"; git add -u' --` to the .pre-commit-config.yaml to enforce the commit.

```sh-4.2$ cat .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        entry: bash -c 'black "$@"; git add -u' --
```

But a better solution would be to handle the error and give the user the possibility to check files after black run.

## Reproduce

1. `pip install pre-commit` and create a `.pre-commit-config.yaml` as seen above **without** the line `entry: bash -c 'black "$@"; git add -u' --` in the repo root
2. Change any file
3. Go to 'Jupyterlab git interface'
4. Click on 'stage'
5. See error: 'Unhandled error'

## Expected behavior

Like in commandline:
`git commit -am "message"`
pre-commit-hook is executed - black codeformatter formats some files: `- files were modified by this hook`

After that a `git commit -am "message"` is executed and the commit happens without any error.

## Context

- Python package version:

jupyterlab-git            0.9.0                     <pip>
- Extension version:

JupyterLab v1.2.6
Known labextensions:
   app dir: /home/ec2-user/anaconda3/envs/JupyterSystemEnv/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @jupyterlab/celltags v0.2.0  enabled  OK
        **@jupyterlab/git v0.9.0  enabled  OK**
        @jupyterlab/toc v1.0.1  enabled  OK
        jupyter-matplotlib v0.5.0  enabled  OK
        jupyterlab-plotly v1.5.2  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled  OK
        plotlywidget v1.5.2  enabled  OK
        sagemaker_examples v0.1.0  enabled  OK
        sagemaker_session_manager v0.1.0  enabled  OK
<details><summary>Command Line Output</summary>
<pre>
[E 09:27:23.712 NotebookApp] Uncaught exception POST /git/commit?1582709243094 (10.0.1.53)
    HTTPServerRequest(protocol='https', host='x.x.x.x:8443', method='POST', uri='/git/commit?1582709243094', version='HTTP/1.1', remote_ip='x.x.x.x')
    Traceback (most recent call last):
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/jupyterlab_git/handlers.py", line 350, in post
        my_output = self.git.commit(commit_msg, top_repo_path)
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/site-packages/jupyterlab_git/git.py", line 694, in commit
        ["git", "commit", "-m", commit_msg], cwd=top_repo_path
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'dsfgfdffg']' returned non-zero exit status 1.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
not available
</pre>
</details>

**Comment by telamonian** [comment] 2020-03-04 21:08
Personally, I like the approach that lint-staged takes, where it will automagically stage changes made by the linter during a pre-commit hook. However, the guy responsible for both black and pre-commit [apparently *hates* this](https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080):

> pre-commit itself will never touch the staging area. These are good ways to silently break commits. In my mind this is one of the worst things that lint-staged does and suggests -- hooks are very frequently not perfect and magically changing what's being committed should not be taken lightly.
> 
> That said, if you would like to foot gun, your hook can call `git add -u` and pre-commit won't know any better :) a sketch of that (untested, discouraged)
> 
> ```yaml
>   - id: yapf
>     entry: bash -c 'yapf "$@"; git add -u' --
> ```
> 
> (note: using bash will potentially reduce portability)

@sutiv Since the issue you're running into is black working as intended, and since there's a published and widely known workaround, I'm closing this as Won't Fix

**Closed by telamonian** 2020-03-04 21:08 UTC
Labels: status:Wont Fix, tag:Documentation

**Comment by sutiv** [comment] 2020-03-06 05:34
hi @telamonian, i got two more points... 

the first is only for information:
* the "hack" works only inside jupytlerlab or under unix systems, some of our developers use windwos locally without jupyterlab but with our main repository

the second one is my wish
* i dont need the second commit automatically, it is good enough if the user can do the commit again in your extension by clicking on commit. the problem i described above, is that the user cant click a second time.... so you have to handle the exception in order to allow a second commit

if this is done, we will remove the hack and everybody has to do two commits, it does not make a difference if he is using a commandline or your extension...
