### ISSUE TITLE
JupyterLab-Git not visible through JupyterHub

### ISSUE THREAD

**Issue by ozone1991** [jupyterlab/jupyterlab-git#185] opened 2018-03-14 14:06 UTC
Hi,

So I have successfully installed the extension and it is available when I launch JupyterLab. However, when I am using JupyterLab through JupyterHub, the extension does not appear. Any ideas what this could be?

**Comment by zzhangjii** [comment] 2018-03-14 22:02
Thanks for reporting this issue, we haven't test this git-extension through Jupyterhub.
First, make sure JupyterHub is running locally;
If installed JupyterLab on a system running JupyterHub,  it should be available at the` /lab` URL.
Are there any error info in the console saying 'git-extension loading failed?'

**Comment by ozone1991** [comment] 2018-03-15 09:54
Thanks for the reply. I got it sorted. Turns out my JupyterLab application directory in JupyterHub was
 
/pathto/anaconda5/envs/py36/share/jupyter/lab

when it should be:

/pathto/anaconda5/share/jupyter/lab

and the directory it was reading from didn't contain the extension in the extensions sub-folder.

I fixed it by copying the tgz file in /pathto/anaconda5/share/jupyter/lab/extensions to /pathto/anaconda5/envs/py36/share/jupyter/lab/extensions and rebuilt the JupyterLab package with /pathto/anaconda5/envs/py36/bin/jupyter lab build. I've obviously made an error in my JupyterHub install somewhere along the way. Just thought I would leave a comment for if anyone runs into the same problem as me in future.

**Comment by dhirschfeld** [comment] 2018-08-28 00:42
It looks like this issue is caused by installing the extension into a different environment than the one running JupyterLab and as such it can probably be closed?

**Comment by ellisonbg** [comment] 2018-10-15 16:17
Closing for now, please let us know if this shows up again.

**Closed by ellisonbg** 2018-10-15 16:17 UTC
