### ISSUE TITLE
CLONE to root works else Error 500 

### ISSUE THREAD

**Issue by vagarwal77** [jupyterlab/jupyterlab-git#720] opened 2020-08-09 01:09 UTC
Hi, 

Whenever i am cloning to the root, it is working fine with status 200 else, all the failures as below. Please suggest how to workaround it? 

root@ip-10-164-10-57:/# jupyter serverextension list 
config dir: /usr/local/etc/jupyter
    jupyterlab  enabled 
    - Validating...
      jupyterlab 2.2.2 OK
    jupyterlab_git  enabled 
    - Validating...
      jupyterlab_git 0.20.0 OK
    nbdime  enabled 
    - Validating...
      nbdime 2.0.0 OK

I am struggling and seems like many others had the similar issue (last comment of https://github.com/jupyterlab/jupyterlab-git/issues/497)

http://internal-ai-core-load-balancer-1129671108.us-east-1.elb.amazonaws.com:8000/user/vagarwal/git/clone?1596934121737

{"message": "Unhandled error", "reason": null, "traceback": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/tornado/web.py\", line 1703, in _execute\n    result = await result\n  File \"/usr/local/lib/python3.7/site-packages/jupyterlab_git/handlers.py\", line 41, in post\n    data[\"current_path\"], data[\"clone_url\"], data.get(\"auth\", None)\n  File \"/usr/local/lib/python3.7/site-packages/jupyterlab_git/git.py\", line 258, in clone\n    env=env,\n  File \"/usr/local/lib/python3.7/site-packages/jupyterlab_git/git.py\", line 123, in execute\n    None, call_subprocess, cmdline, cwd, env\n  File \"/usr/local/lib/python3.7/concurrent/futures/thread.py\", line 57, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/jupyterlab_git/git.py\", line 92, in call_subprocess\n    cmdline, stdout=subprocess.PIPE, stderr=subprocess.PIPE, cwd=cwd, env=env\n  File \"/usr/local/lib/python3.7/subprocess.py\", line 800, in __init__\n    restore_signals, start_new_session)\n  File \"/usr/local/lib/python3.7/subprocess.py\", line 1551, in _execute_child\n    raise child_exception_type(errno_num, err_msg, err_filename)\nFileNotFoundError: [Errno 2] No such file or directory: '/s3': '/s3'\n"}

![image](https://user-images.githubusercontent.com/46463536/89722536-a72a5280-d9b8-11ea-8dfd-8b0c4b6f2e0e.png)

**Comment by fcollonval** [comment] 2020-08-23 20:58
Hey @vagarwal77 sorry for the late answer, can you access the `/s3` directory from the terminal? 

I remembered that amazon is using some specific plugin to serve data within JupyterLab.

**Comment by fcollonval** [comment] 2020-11-01 09:49
Duplicate of #684

**Closed by fcollonval** 2020-11-01 09:49 UTC
Labels: status:Needs Info, type:Bug
