### ISSUE TITLE
Git diffing of non-notebook files fails with an error

### ISSUE THREAD

**Issue by slenky** [jupyterlab/jupyterlab-git#830] opened 2020-11-26 09:12 UTC
## Description

We have a custom JupyterLab image with git repository inside /home/kflovian/scripts baked-on Azure Fileshare (issue confirmed on both SMB & NFS shares) & mounted as Kubernetes volume.
In hybridcontents it's been configured as FileContentManager with `root_dir:  /home/kflovian/scripts`.

Trying to diff any notebook file works but all the other text files fail with an error:
![image](https://user-images.githubusercontent.com/1599647/100329523-6e999d80-2fd6-11eb-96c7-ea9e482d565d.png)

Same error in the logs with 404.

## Reproduce

1. Initialise a repo in /home/kflovian/scripts
2. Commit a new txt file
3. Do some changes in that file
4. Click on 'Diff'

## Expected behavior

Git diffing works properly.

## Context

- Python package version:
```
jupyterlab-git            0.23.1
hybridcontents            0.3.0
```
- Extension version:
```
JupyterLab v2.2.9
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyterlab/debugger v0.3.5  enabled  OK
        @jupyterlab/git v0.23.1  enabled  OK
        nbdime-jupyterlab v2.0.1  enabled  OK
```
- Git version:
git version 2.25.1
- Operating System and its version:
Ubuntu 20 Docker image
<details><summary>Command Line Output</summary>
<pre>
[W 09:59:01.944 LabApp] 404 POST /notebook/bohdana/test/git/diffcontent?1606381141521 (127.0.0.1): Couldn't resolve path [home/kflovian/scripts/test1.txt] and no root manager supplied!
[W 09:59:01.945 LabApp] Couldn't resolve path [home/kflovian/scripts/test1.txt] and no root manager supplied!
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
Same error as above.
</pre>
</details>

**Comment by fcollonval** [comment] 2020-11-26 10:54
Hey @slenky, 

Thank you for reporting. This is quite tricky to solve as hybridcontent manager does not by design follows the one root directory design of the default content manager.

If you are willing to contribute a fix on this, I happily share with you some pointers to do so.

This is a duplicate of #684. So I'm closing this issue.

**Closed by fcollonval** 2020-11-26 10:54 UTC
Labels: type:Bug
