### ISSUE TITLE
Install error - yarn network connection

### ISSUE THREAD

**Issue by joelion** [jupyterlab/jupyterlab-git#420] opened 2019-10-03 23:26 UTC
I am behind a corporate proxy. However, I have all of my proxy and ssl settings set up in `~/.npmrc` and `~/.yarnrc`, and use `npm` to install things all the time. 

I've installed various other labextensions with no problem, but jupyterlab-git extension fails when I install it using `jupyter labextension install @jupyterlab/git` or if I clone and install directly. It always fails at:

```
Building jupyterlab assets (build:prod:minimize)
> node /u/dramsoft/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.19.0
[1/5] Validating package.json...
[2/5] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error Couldn't find package "nbdime@~5.0.1" required by "@jupyterlab/git@file:../extensions/jupyterlab-git-0.8.2.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


npm dependencies failed to install
Traceback (most recent call last):

  File "/u/dramsoft/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/u/dramsoft/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    core_config=self.core_config)

  File "/u/dramsoft/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

  File "/u/dramsoft/miniconda3/envs/jupyterhub/lib/python3.7/site-packages/jupyterlab/commands.py", line 574, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install

Exiting application: jupyter

```

Whenever I search for yarn installation problems, the solution always seems to increase the network-timeout. I've done that in `~/.yarnrc`, but I don't think it's taking effect. I updated `site-packages/jupyterlab/staging/.yarnrc`, and confirmed this .yarnrc was being copied into the `jupyter/lab/staging` area, but again, same error. 

I can run standalone `npm` and download the `nbdime` package that is failing in yarn. 

So what other settings can I change, or can I force to install with npm instead of yarn?

**Comment by fcollonval** [comment] 2019-10-06 18:56
Could you try to request information on the missing package?
```bash
jlpm info nbdime
```

Usually the error `info There appears to be trouble with your network connection. Retrying...` has one of the following root causes:
- Bad internet connection
- Wrong yarn configuration (more probable in company infrastructure)

Your problem could be hard to solve, because in addition to be behind a corporate proxy, it looks like you are not using `jlpm` (the yarn packaged with jupyterlab). In your log, the version reported is 1.19.0 but jupyterlab should be built with 1.15.2.

**Comment by marskar** [comment] 2019-10-18 23:02
Could conda environments help to fix this dependency issue?
I have the same problem and I'm trying to solve this with the following conda command`conda create -n jupy -yc conda-forge jupyterlab-git nodejs yarn=1.15.2`

**Comment by marskar** [comment] 2019-10-18 23:55
I also got it to work outside of a conda env with yarn 1.19. 

<details>
 <summary>Results of `conda list` outside of any conda env</summary>
```sh
# packages in environment at /home/USERNAME/miniconda3: 
#
# Name                    Version                   Build  Channel       
_libgcc_mutex             0.1                        main
asn1crypto                0.24.0                   py37_0
attrs                     19.2.0                     py_0    conda-forge 
backcall                  0.1.0                      py_0    conda-forge 
bleach                    3.1.0                      py_0    conda-forge 
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.9.11            hecc5488_0    conda-forge 
certifi                   2019.9.11                py37_0    conda-forge 
cffi                      1.12.3           py37h2e261b9_0
chardet                   3.0.4                    py37_1
colorama                  0.4.1                    pypi_0    pypi        
conda                     4.7.12                   py37_0    conda-forge 
conda-package-handling    1.3.11                   py37_0
cryptography              2.7              py37h1ba5d50_0
decorator                 4.4.0                      py_0    conda-forge 
defusedxml                0.6.0                      py_0    conda-forge 
entrypoints               0.3                   py37_1000    conda-forge 
gitdb2                    2.0.6                      py_0    conda-forge 
gitpython                 3.0.3                      py_0    conda-forge 
icu                       64.2                 he1b5a44_1    conda-forge 
idna                      2.8                      py37_0
importlib_metadata        0.23                     py37_0    conda-forge 
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge 
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge 
ipython-genutils          0.2.0                    pypi_0    pypi        
ipython_genutils          0.2.0                      py_1    conda-forge 
jedi                      0.15.1                   py37_0    conda-forge 
jinja2                    2.10.3                     py_0    conda-forge 
json5                     0.8.5                      py_0    conda-forge 
jsonschema                3.1.1                    py37_0    conda-forge 
jupyter-client            5.3.4                    pypi_0    pypi        
jupyter-core              4.6.0                    pypi_0    pypi        
jupyter_client            5.3.3                    py37_1    conda-forge 
jupyter_core              4.5.0                      py_0    conda-forge 
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab-git            0.8.2                     dev_0    <develop>
jupyterlab_server         1.0.6                      py_0    conda-forge
libarchive                3.3.3                h5d8350f_5
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4   
libgcc-ng                 9.1.0                hdf63c60_0
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libuv                     1.32.0               h516909a_0    conda-forge 
libxml2                   2.9.9                hea5a465_1
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h49e0be7_2
markupsafe                1.1.1            py37h14c3975_0    conda-forge 
mistune                   0.8.4           py37h14c3975_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbdime                    1.1.0                    py37_0    conda-forge
nbformat                  4.4.0                    pypi_0    pypi 
ncurses                   6.1                  he6710b0_1
nodejs                    12.11.1              h10a4023_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge 
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.1                      py_0    conda-forge 
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.1.1                   py37_0
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge 
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pygments                  2.4.2                      py_0    conda-forge 
pyopenssl                 19.0.0                   py37_0
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                      py_0    conda-forge 
python-libarchive-c       2.8                     py37_11
pyzmq                     18.1.0                   pypi_0    pypi
readline                  7.0                  h7b6447c_5   
requests                  2.22.0                   py37_0
ruamel_yaml               0.15.46          py37h14c3975_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0   
smmap2                    2.0.5                      py_0    conda-forge
sqlite                    3.29.0               h7b6447c_0
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.8                hbc83047_0
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.32.1                     py_0
traitlets                 4.3.3                    py37_0    conda-forge 
urllib3                   1.24.2                   py37_0
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3   
zstd                      1.3.7                h0b5b093_0
```
</details>


<details>
 <summary>Results of `conda list` inside of my `base` conda env</summary>
```sh
# packages in environment at /home/USERNAME/miniconda3: 
#
# Name                    Version                   Build  Channel       
_libgcc_mutex             0.1                        main
asn1crypto                0.24.0                   py37_0
attrs                     19.2.0                     py_0    conda-forge 
backcall                  0.1.0                      py_0    conda-forge 
bleach                    3.1.0                      py_0    conda-forge 
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2019.9.11            hecc5488_0    conda-forge 
certifi                   2019.9.11                py37_0    conda-forge 
cffi                      1.12.3           py37h2e261b9_0
chardet                   3.0.4                    py37_1
colorama                  0.4.1                    pypi_0    pypi        
conda                     4.7.12                   py37_0    conda-forge 
conda-package-handling    1.3.11                   py37_0
cryptography              2.7              py37h1ba5d50_0
decorator                 4.4.0                      py_0    conda-forge 
defusedxml                0.6.0                      py_0    conda-forge 
entrypoints               0.3                   py37_1000    conda-forge 
gitdb2                    2.0.6                      py_0    conda-forge 
gitpython                 3.0.3                      py_0    conda-forge 
icu                       64.2                 he1b5a44_1    conda-forge 
idna                      2.8                      py37_0
importlib_metadata        0.23                     py37_0    conda-forge 
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge 
ipython                   7.8.0            py37h5ca1d4c_0    conda-forge 
ipython-genutils          0.2.0                    pypi_0    pypi        
ipython_genutils          0.2.0                      py_1    conda-forge 
jedi                      0.15.1                   py37_0    conda-forge 
jinja2                    2.10.3                     py_0    conda-forge 
json5                     0.8.5                      py_0    conda-forge 
jsonschema                3.1.1                    py37_0    conda-forge 
jupyter-client            5.3.4                    pypi_0    pypi        
jupyter-core              4.6.0                    pypi_0    pypi        
jupyter_client            5.3.3                    py37_1    conda-forge 
jupyter_core              4.5.0                      py_0    conda-forge 
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab-git            0.8.2                     dev_0    <develop>
jupyterlab_server         1.0.6                      py_0    conda-forge
libarchive                3.3.3                h5d8350f_5
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4   
libgcc-ng                 9.1.0                hdf63c60_0
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libuv                     1.32.0               h516909a_0    conda-forge 
libxml2                   2.9.9                hea5a465_1
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h49e0be7_2
markupsafe                1.1.1            py37h14c3975_0    conda-forge 
mistune                   0.8.4           py37h14c3975_1000    conda-forge
more-itertools            7.2.0                      py_0    conda-forge
nbconvert                 5.6.0                    py37_1    conda-forge
nbdime                    1.1.0                    py37_0    conda-forge
nbformat                  4.4.0                    pypi_0    pypi 
ncurses                   6.1                  he6710b0_1
nodejs                    12.11.1              h10a4023_0    conda-forge
notebook                  6.0.1                    py37_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge 
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.1                      py_0    conda-forge 
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pip                       19.1.1                   py37_0
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge 
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pygments                  2.4.2                      py_0    conda-forge 
pyopenssl                 19.0.0                   py37_0
pyrsistent                0.15.4           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                      py_0    conda-forge 
python-libarchive-c       2.8                     py37_11
pyzmq                     18.1.0                   pypi_0    pypi
readline                  7.0                  h7b6447c_5   
requests                  2.22.0                   py37_0
ruamel_yaml               0.15.46          py37h14c3975_0
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0
six                       1.12.0                   py37_0   
smmap2                    2.0.5                      py_0    conda-forge
sqlite                    3.29.0               h7b6447c_0
terminado                 0.8.2                    pypi_0    pypi
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.8                hbc83047_0
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.32.1                     py_0
traitlets                 4.3.3                    py37_0    conda-forge 
urllib3                   1.24.2                   py37_0
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.4                   py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11               h7b6447c_3   
zstd                      1.3.7                h0b5b093_0
```
</details>

Interestingly, whenever I run `npm list`, I always get 
```
/mnt/c/Users/USERNAME
└── yarn@1.19.1
```
even if I am in a conda environment with the yarn version pinned to 1.15.2!

**Comment by marskar** [comment] 2019-10-19 00:08
text

**Comment by joelion** [comment] 2019-10-22 21:38
@fcollonval  - i am using the `jlpm` bundled in JupyterLab, and it is 1.15.2. The 1.19.0 you were seeing was my `yarn` version. Or, should `jlpm` and `yarn` be the same version...? Below is the yarn error when I run `jlpm install`

```
$ which yarn
/u/dramsoft/miniconda3/envs/jupyterhub/bin/yarn

$ yarn --version
1.19.0

$ which jlpm
/u/dramsoft/miniconda3/envs/jupyterhub/bin/jlpm

$ jlpm --version
1.15.2

$ jlpm install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab/coreutils/-/coreutils-3.1.0.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/home/dramsoft/jupyterhub/extensions/jupyterlab-git/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
```

Thanks @marskar. I, too, downloaded `jupyterlab-git` and tried to install it from source, but I run into the same error when it tries to install dependencies.

**Comment by fcollonval** [comment] 2019-11-14 08:28
@joelion from the error 
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@jupyterlab/coreutils/-/coreutils-3.1.0.tgz: ESOCKETTIMEDOUT".
```

It confirms your connection is very slow or not properly set. When executing `jlpm install`, have the `node_modules` started to be populated by some folders? 

If yes, you probably have a very slow connection. So try multiple time `jlpm install`. At some point, it won't fail. Then, all packages being cached, you will be able to install the extension through `jupyter labextension install .`.

**Comment by telamonian** [comment] 2019-12-05 06:58
@joelion I'm closing this for now since there's been no new activity for a while (and it's unclear how general an issue this is), but if you want to work on this further please feel free to reopen.

**Closed by telamonian** 2019-12-05 06:58 UTC
Labels: tag:Build System, type:Question

**Comment by joelion** [comment] 2019-12-05 19:38
@telamonian thanks, i haven't had time to debug this any more, but when I get back to it I'll, re-open

**Comment by timenet2300** [comment] 2022-05-08 05:55
check this: conda install -c conda-forge nodejs. it might work
