### ISSUE TITLE
Status widget distracts with frequent visual disturbance (refreshing->idle->refreshing->…)

### ISSUE THREAD

**Issue by flying-sheep** [jupyterlab/jupyterlab-git#872] opened 2021-02-10 11:50 UTC
## Description

After installing Jupyerlab-Git, the status widget is constantly visually busy by changing its status from “idle” to “refreshing…” and back every second or so.

The severity is increased by the widget being on the left of the status bar, moving all other widgets around when changint its width.

## Reproduce

Open Jupyterlab outside of a git repo with Jupyterlab-Git installed.

## Expected behavior

No change to the status widget when nothing out of the ordinary is happening.

**Comment by fcollonval** [comment] 2021-02-10 12:01
Hey @flying-sheep 

This is a duplicate of #803 - you will find more information there. As of today, you can turn it off using by turning the `displayStatus` setting to `false`.

**Closed by fcollonval** 2021-02-10 12:02 UTC
Labels: status:Duplicate, type:Bug

**Comment by flying-sheep** [comment] 2021-02-10 16:56
sorry, couldn’t find it, should have looked harder
