### ISSUE TITLE
Feature request: an option to ignore output cells

### ISSUE THREAD

**Issue by jej** [jupyterlab/jupyterlab-git#846] opened 2020-12-19 11:47 UTC
## Is your feature request related to a problem? Please describe.

I use this git extension to code under Micropython. Many times the cell outputs are not important, because there are just running outputs or scrambled serial data from the microcontroller. I don't need to commit this information. I would like an option to ignore output cells.

## Describe the solution you'd like

An option to ignore the output cells (for diffs, commits, etc). So only code cells are relevant for the git operations.

## Describe alternatives you've considered

I clear manually the output cells before comparing or committing.

Thanks for this extension, very useful anyway.

## Additional context

- Python package version:

- Extension version:

- Git version:

- Operating System and its version:

**Comment by fcollonval** [comment] 2020-12-21 17:17
@jej Thanks for voicing out your idea. But I'm closing this one as it is a duplicate of #392.

**Closed** 2020-12-21 17:17 UTC
Labels: type:Enhancement
