### ISSUE TITLE
Git clone or push does not work for repositories requiring authentication

### ISSUE THREAD

**Issue by wno-xyt** [jupyterlab/jupyterlab-git#1309] opened 2023-12-13 10:38 UTC
## Description
When trying to clone(or push) a repository using jupyterlab-git extension the following message appears:

![image](https://github.com/jupyterlab/jupyterlab-git/assets/17002041/2fcd0779-ae4b-4ce8-8ec9-93d24bbd748d)

Opening terminal and cloning or pushing the same repo with same user using cmdline works.

## Reproduce

1. Go to 'Git -> Clone a repository'
2. Select a repository requiring authentication 
3. Provide username and token
4. See error as per above screenshot

While reporoducing it in container I can see the following stack trace:

## Context

- Python package version:
```
(base) jovyan@27163b7383cc:~$ conda list jupyterlab-git
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
jupyterlab-git            0.50.0                   pypi_0    pypi
```
- Extension version:
```
jupyter labextension list
JupyterLab v4.0.9
/opt/conda/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        nbdime-jupyterlab v3.0.1 enabled OK
        jupyterlab-plotly v5.18.0 enabled  X
        jupyter-matplotlib v0.11.3 enabled OK
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyterlab/git v0.50.0 enabled OK (python, jupyterlab-git)
        @jupyterhub/jupyter-server-proxy v4.1.0 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments
        jupyterlab-plotly
        
   Consider checking if an update is available for these packages.
```

- Git version:
```
(base) jovyan@27163b7383cc:~$ git --version
git version 2.34.1
```

- Operating System and its version:
This is docker container (slightly modified): 
`jupyter/scipy-notebook:x86_64-lab-4.0.7`

Cloning a public repo that does not require authentication works without problems.

Any hints on how to fix this or any workarounds?

**Comment by clabnet** [comment] 2023-12-13 21:09
Also for me, same issue.

**Comment by skender18** [comment] 2023-12-19 10:24
I got the same issue with python 3.11.6

**Comment by wno-xyt** [comment] 2023-12-19 10:30
For the ones using docker image we found a workaround to have working image:
```
FROM jupyter/scipy-notebook:x86_64-lab-4.0.7

#Your custom stuff for image goes here.

RUN pip install git+https://github.com/pexpect/pexpect.git@master
RUN mamba install --yes \
    'jupyterlab-git==0.50.0' \
    'jupyterlab==4.0.8' && \
    mamba clean --all -f -y && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"
```

With this we have a docker image with working cloning and pushing.
Hope this helps.

**Comment by fcollonval** [comment] 2023-12-19 14:23
Yes the issue is the one of `pexpect`: https://github.com/jupyterlab/jupyterlab-git/issues/1261

Closing this one as duplicate.

**Closed by fcollonval** 2023-12-19 14:23 UTC
Labels: bug
