### ISSUE TITLE
Visual regression on 0.22

### ISSUE THREAD

**Issue by elgalu** [jupyterlab/jupyterlab-git#795] opened 2020-10-08 14:36 UTC
Hi, anyone else started experiencing this visual issue after the upgrade?

![image](https://user-images.githubusercontent.com/111569/95473381-574e1480-0984-11eb-8df1-ef2304beb8df.png)

**Comment by fcollonval** [comment] 2020-10-09 06:12
Hey yes this is a duplicate of #793. There is a patch on the way to be released within the next hours.

**Closed by fcollonval** 2020-10-09 06:12 UTC
