### ISSUE TITLE
Notebook edition acquires annoying interruptions

### ISSUE THREAD

**Issue by restrepo** [jupyterlab/jupyterlab-git#637] opened 2020-05-08 04:07 UTC
## Description
Jupyter lab unresponsive after install jupyterlab-git
## Reproduce

1. Clean install of jupyter-lab 
2. Open to a notebook with a code cell  with at least 10 lines of code
3. Move the cursor horizontally and check that flows with no interruptions
4. Install jupyterlab-git according to the README.md instructions
5. Go to the previous cell with the new installation
4. Move the cursor horizontally: now this stop for a while every 150 characters or so. In general, the 
    notebook edition becomes quite unresponsive
5. Uninstall jupyterlab-git and everything returns back to normal

## Expected behavior

Installation of the extension could not affect the usability of the notebooks

## Context

- Python package version: 3.5

- Extension version:  jupyterlab-git-0.20.0

```
JupyterLab v2.1.1
Known labextensions:
   app dir: /usr/local/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/shortcutui v0.5.0-beta.2  enabled  OK
        @reviewnb/jupyterlab_gitplus v0.1.3  enabled  OK
        jupyterlab-jupytext v1.2.1  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
```

**Comment by fcollonval** [comment] 2020-05-18 07:30
@restrepo Thanks for reporting. This one is gonna be complicated - especially as everything should be asynchronous now. I'll need to try installing your stack on Python 3.5; from your app directory, I presume you have a Linux OS.

In the meantime, there is one parameter you may try to play with:

```json
"refreshInterval": {
      "type": "integer",
      "title": "Refresh interval",
      "description": "Number of milliseconds between polling the file system for changes.",
      "default": 3000
    }
```

Could you go in JupyterLab to Advanced Settings -> Git and increase that number to see if it has any impact on your use case?

**Comment by restrepo** [comment] 2020-05-18 16:11
I can confirm that increasing the `refrehInterval` setting immediately improves the responsiveness of the interactions of the notebook. I confirm that I have a Debian 9 install.

**Comment by ianhi** [comment] 2020-06-11 21:38
Hey @restrepo how large is the Git repository you are using? Do you experience the same interruptions when not in a Git repository, or when in an empty repo? It's possible this is being caused by a large number of files as in https://github.com/jupyterlab/jupyterlab-git/issues/667

**Comment by fcollonval** [comment] 2020-11-01 09:55
Closing this one as virtualizing the files list probably fixed it.

**Closed by fcollonval** 2020-11-01 09:55 UTC
Labels: type:Enhancement
