### ISSUE TITLE
Compatibility with JupyterLab 3.0?

### ISSUE THREAD

**Issue by jameslao** [jupyterlab/jupyterlab-git#851] opened 2020-12-28 01:24 UTC

**Comment by BugzTheBunny** [comment] 2020-12-28 14:36
same question here.
It works by iteself, but when i install and rebuild, it takes my JupyterLab back to 2.2.9 after the build.

**Comment by fcollonval** [comment] 2020-12-28 16:56
Duplicate of #779 

Please subscribe to that issue if you want to be notified about update on that subject.

**Closed by fcollonval** 2020-12-28 16:56 UTC
Labels: type:Enhancement
