### ISSUE TITLE
Installation issue from JupyterLab extension manager

### ISSUE THREAD

**Issue by jaipreet-s** [jupyterlab/jupyterlab-git#341] opened 2019-04-17 17:28 UTC
> The front page directions do work after upgrading jupyter lab to the latest.
> 
> ```
> jupyter labextension install @jupyterlab/git
> pip install jupyterlab-git
> jupyter serverextension enable --py jupyterlab_git
> ```

I originally installed the extension with via the UI (ext manager) but couldn't get it to work. 

Running the steps above from the command line solved the issue!

_Originally posted by @lambdamusic in https://github.com/jupyterlab/jupyterlab-git/issues/212#issuecomment-483984286_

**Comment by saulshanabrook** [comment] 2019-04-18 17:02
This is a fundamental issue with the extension manager. It cannot install any server extensions only client side ones.

We could try to extend it to handle Python dependencies with conda or pip, but this would require some work.

What about improving our current error message if they don't have the server extension installed and enabled?

**Comment by jaipreet-s** [comment] 2019-04-18 17:10
> We could try to extend it to handle Python dependencies with conda or pip, but this would require some work.

Is there an issue on the JL repo that we can reference?

**Comment by saulshanabrook** [comment] 2019-04-22 17:06
@jaipreet-s I just opened https://github.com/jupyterlab/jupyterlab/issues/6228 because I couldn't find an existing one. I think that covers it.

**Comment by vidartf** [comment] 2019-04-24 00:10
Note: I had some code previously in jupyterlab-discovery to do this. It should be reasonable to open that as a PR to lab. I just need some spare time (I have a bit of backlog to catch up on).

**Comment by vidartf** [comment] 2019-04-24 00:12
Note: There are metadata that you can add to the package.json that will let prompt the extension manager to display a dialog to the user. It will give a warning, and suggest a command to run. I think it is documented, but it might not be, I will have to check.

**Comment by jaipreet-s** [comment] 2019-04-25 23:20
> Note: There are metadata that you can add to the package.json that will let prompt the extension manager to display a dialog to the user. It will give a warning, and suggest a command to run. I think it is documented, but it might not be, I will have to check.

@vidartf : That sounds like a great first step. Please let us know if you find that package.json setting

**Comment by vidartf** [comment] 2019-04-26 11:16
https://jupyterlab-discovery.readthedocs.io/en/stable/extension-authors.html#companion-packages

**Comment by fcollonval** [comment] 2019-10-20 10:15
Some additional thoughts about installation of extension with both a front and a backend:

I think bumping versions post release is a good idea. It's been standard practice in core and a bunch of other extensions. In spite of my earlier speculation, I actually don't think it would have helped fix the trouble I ran into with an old version of labextension getting installed (on a low level, it had to do with the missing schema dir and how `labextension install` validates packages (and how it falls back when that validation fails)). The cache problem was then caused by the fact that `pip`'s wheel cache won't automatically rebuild if the only thing that changes is the labextension `.tgz`.

In light of the additions made in this PR and others (eg #426), I bumped the versions of both labextension and Python package to `0.9.0`.

Bundling the Typescript code into the Python package honestly smells like an anti-pattern to me. Beyond the issues I ran into, there's a bunch of other obvious problems. For example, every time there's a new release of the labextension, we'll also have to do a new release of the Python package, even if there's no changes to the Python code. A better solution would be to just call out to the `labextension` app in `setup.py` (`jupyter labextension install jupyterlab_git` for release, `jupyter labextension install .` for develop). But let's save hashing that out for another PR.

_Originally posted by @telamonian in https://github.com/jupyterlab/jupyterlab-git/pull/424#issuecomment-544237642_

**Comment by telamonian** [comment] 2019-12-05 06:27
A real solution to this issue would require significant enhancements to the labextension GUI in core. These likely won't happen, since the current plan is to jettison the labextension manager from core entirely. Instead we'll bundle each plugin's lab- and/or serverextension together in a single Python package, and then let `pip`/`conda` sort out everything else. So in that sense, this issue is a won't fix.

On the bright side, after the work done in #415 and #458, an end user need only now install the `pip` package and then (re)build the app:

```
pip install jupyterlab-git
jupyter lab build
```

in order to get a completely functional instance `@jupyterlab/git` plugin running. So that at least addresses the concern of an end-user needing to grasp the lab/serverextension distinction

**Closed by telamonian** 2019-12-05 06:27 UTC

**Comment by vidartf** [comment] 2019-12-05 10:27
Note for completeness: just because we are changing the plugin distribution and build system in Jupyterlab does not entail that we will stop having a UI frontend for discovering and managing extensions. It will close this issue though (assuming that the current plan ends up working).

**Comment by telamonian** [comment] 2019-12-05 10:53
> (assuming that the current plan ends up working).

That is an important assumption

> does not entail that we will stop having a UI frontend for discovering and managing extensions

That is a good point, and I did not mean to gloss over it. We will still have our own tools/UI for discovery and (probably) management. The pertinent big change from the perspective of a user is that there will be a single source from which all jupyterlab extensions will be installed, instead of some things coming from the labextension manager and some things coming from `pip`
