### ISSUE TITLE
Dropdown overflows resulting in scrollbars

### ISSUE THREAD

**Issue by joctee** [jupyterlab/jupyterlab-git#820] opened 2020-11-09 15:29 UTC
## Description

In JupyterLab, when I use an ipywidget.Dropdown without a description, everything looks as expected. However, when I add a description, it looks like the div overflows resulting in a scrollbar being shown:

![image](https://user-images.githubusercontent.com/25039546/98533982-0e8bc300-2284-11eb-9d1e-83fbac60520e.png)

I'm not sure if this is an ipywidget or a JupyterLab problem.

If I disable the ".jupyter-widgets {overflows: auto !important;}" rule from Chrome's DevTools then the scrollbar disappears. But this is causing other unwanted side-effects such as some widgets getting wider than my screen.

![image](https://user-images.githubusercontent.com/25039546/98535515-86f38380-2286-11eb-91cf-31631cd0d9a2.png)

## Reproduce

Run this in an empty cell:
```
import ipywidgets
ipywidgets.Dropdown(options=['test'], description='Test')
```

## Expected behavior

No scrollbars should be visible.

## Context

- Python package version:
```
ipywidgets                7.5.1
jupyter                   1.0.0
jupyter_client            6.1.7
jupyter_console           6.2.0
jupyter_core              4.6.3
jupyterlab                2.2.6 (<---I have also tried with 2.2.9 and 2.3.0a1)
jupyterlab_pygments       0.1.2
jupyterlab_server         1.2.0
```
- Extension version:
```
$ jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/joctee/anaconda_20201106/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyterlab-plotly v4.12.0  enabled  OK
        plotlywidget v4.12.0  enabled  OK
        qgrid2 v1.1.3  enabled  OK*

   local extensions:
        qgrid2: /home/joctee/dev/qgrid/js
```
- Git version:
```
git version 2.28.0
```

**Comment by ianhi** [comment] 2020-11-09 17:09
Hey @joctee I think you may have ended up on the incorrect repo. This repo is for the jupyterlab extension to manage git repositories so I'm going to close this. I'd recommend opening the issue on the ipywidgets repo: https://github.com/jupyter-widgets/ipywidgets

One extra thing to check when you transfer the issue is whether or not the same issue exists in both jupyter notebook and jupyter lab

**Closed by ianhi** 2020-11-09 17:09 UTC

**Comment by ianhi** [comment] 2020-11-09 17:11
Also FWIW I am unable to replicate this on Firefox 81, jlab 2.2.9
