### ISSUE TITLE
It is possible to compare two commits with the extension in Jupyterlab?

### ISSUE THREAD

**Issue by lgonzalezsa** [jupyterlab/jupyterlab-git#696] opened 2020-07-15 03:01 UTC
## Description

Similar as using nbdime as follows:
nbdime-web commitA~ commitB -s
Trying to use the extension to compare two random commits.
Was using the extension and not sure how to pick the commit to compare.

Wondering if that can be done with the extension, any guidance more than welcome.

## Expected behavior

Similar as using nbdime as follows:
nbdime-web commitA~ commitB -s

## Context

- Python package version:
# Name                    Version                   Build  Channel
jupyterlab-git            0.20.0                   pypi_0    pypi
- Extension version:
JupyterLab v2.1.5
Known labextensions:
   app dir: C:\Users\gonluisr\Miniconda\envs\jupyterlab-debugger\share\jupyter\lab
        @jupyterlab/debugger v0.2.0 enabled  ok
        @jupyterlab/git v0.20.0 enabled  ok
        @jupyterlab/toc v3.0.0 enabled  ok
        dask-labextension v2.0.2 enabled  ok
        jupyterlab-kernelspy v2.2.0 enabled  ok
        nbdime-jupyterlab v2.0.0 enabled  ok
- Git version:
git version 2.23.0.windows.1
- Operating System and its version:

**Comment by fcollonval** [comment] 2020-07-15 11:56
Hey @lgonzalezsa  unfortunately this is not possible.

**Comment by fcollonval** [comment] 2021-04-03 11:53
Just realize this is a duplicate of #268

**Closed by fcollonval** 2021-04-03 11:53 UTC
Labels: Good first issue, status:Duplicate, type:Enhancement
